[package]
name = "log_limit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.22"
[dev-dependencies]
simple_logger = "5.0.0"
